### ISSUE TITLE
[2.0] web page freezes for a moment

### ISSUE THREAD

**Issue by majkers** [thomasloven/lovelace-card-mod#60]
My Home Assistant version: 0.113

My lovelace configuration method (GUI or yaml): Yaml

What I am doing:

After updating to 2.0.0 version from 14 when entering HA address web page freezes for a couple of seconds. I’ve just installled back 14 version and the freeze is gone. In my java script console all I see is:

`Uncaught (in promise) TypeError: Object(...)()._addCard is not a function`

but it is an error from card-tools and I have as in 2 version as in 14.  I tested in latest firefox and in Edge so I guess Chrome is also affected by this…

What I expected to happen:

No page freeze as in 14 version

What happened instead:

Page freezes fo couple of seconds

Error messages from the browser console:
None for card_mod

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ X] Have made sure I am using the latest version of the plugin.

[ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Please try version 3.0
