### ISSUE TITLE
mod-card MAY cause an error "i.setConfig is not a function"

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-card-mod#323]
2023.12.1
card-mod 3.3.1
Chrome 120.0.6099.129 , Win10x64.

Right after updating to 3.3.1 these errors starting erratically occur.
They are observed for mod-card.

![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/2fe9bb1b-2171-4bd0-9ad3-eb13be1903e3)
```
type: custom:mod-card
card:
  type: vertical-stack
  title: title
  cards:
    - type: entity
      entity: sun.sun
    - type: entity
      entity: sun.sun
```

Sometimes a browser's refresh helps.
In most cases I see these errors after clearing a browser's cache.

Error messages from the browser console:
```
card-mod.js:1 Uncaught TypeError: Illegal constructor
    at new n (card-mod.js:1:10144)
    at o.<anonymous> (card-mod.js:1:9380)
    at new r (card-mod.js:1:15236)
    at o.<anonymous> (card-mod.js:1:9380)
    at new n (card-mod.js:1:32733)
    at o.<anonymous> (card-mod.js:1:9380)
    at new o (card-mod.js:1:45566)
    at C (scoped-custom-element-registry.js:388:7)
    at new t (scoped-custom-element-registry.js:236:11)
    at card-mod.js:1:39893
```

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by tbrasser** [comment]
Also seeing this, and indeed not persistent.

**Comment by thomasloven** [comment]
See #326.
Thanks for pointing out it happened for mod-card. I'd have missed that otherwise.
