### ISSUE TITLE
TypeError: i.setConfig is not a function

### ISSUE THREAD

**Issue by andiukas** [thomasloven/lovelace-card-mod#327]
My Home Assistant version: 2024.1.0b0

My lovelace configuration method (GUI or yaml): yaml

After update to 2024.1.0b0 version, I have error. 

![Screenshot 2023-12-28 072156](https://github.com/thomasloven/lovelace-card-mod/assets/44068098/50d865d8-b97b-44ed-ab44-498b38bb9e24)

**Comment by Mincka** [comment]
Duplicate of #326.
Already fixed in version 3.4.0.

**Comment by andiukas** [comment]
> Duplicate of #323 and by extension of #326. Already fixed in version 3.4.0.

Fix not help :(

**Comment by thomasloven** [comment]
Please use the issue template. That will help you provide enough information for me to have something to work with.
